version: '2.3'

services:

  api:
    image: backend
    restart: always
    build:
      context: backend/app
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000

  web:
    image: frontend
    restart: always
    build:
      context: front-end
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api

networks:
  dev:
    driver: bridge
